const IMPACT_METRICS = [
  {
    icon: "📩",
    value: "11,733",
    label: "Total Messages Handled",
    description: "Every message matters to us",
    color: "from-[#2B00FF]/20 to-[#2B00FF]/5"
  },
  {
    icon: "🤖",
    value: "81.3%",
    label: "Messages Replied by Chatbot",
    description: "Automated with human-like quality",
    color: "from-[#00D4FF]/20 to-[#00D4FF]/5"
  },
  {
    icon: "⏱️",
    value: "5.79s",
    label: "Average Response Time",
    description: "Lightning-fast responses",
    color: "from-[#f6db4b]/20 to-[#f6db4b]/5"
  },
  {
    icon: "💰",
    value: "€1,650",
    label: "Sales Generated by Chatbot",
    description: "Proven ROI for our clients",
    color: "from-[#2B00FF]/20 to-[#00D4FF]/20"
  },
  {
    icon: "✅",
    value: "100%",
    label: "Reduction in Missed Messages",
    description: "Never miss a customer again",
    color: "from-[#00D4FF]/20 to-[#f6db4b]/20"
  }
];

export default function Milestones() {
  return (
    <section className="w-full py-20 bg-gray-900">
      <div className="w-[85%] mx-auto px-6 md:px-12">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <p className="text-sm tracking-widest uppercase text-[#2B00FF] mb-4 font-semibold">Our Impact</p>
            <h2 className="text-4xl sm:text-5xl font-bold text-white mb-6">Our Impact in Numbers</h2>
            <p className="text-xl text-gray-400 max-w-3xl mx-auto mb-8">
              Here's how SparkAI is transforming communication for businesses:
            </p>
            <div className="max-w-4xl mx-auto text-lg text-gray-300 leading-relaxed space-y-2">
              <p>📩 Total Messages Handled: 11,733</p>
              <p>🤖 Messages Replied by Chatbot: 81.3%</p>
              <p>⏱️ Average Response Time: 5.79 seconds</p>
              <p>💰 Sales Generated by Chatbot: €1,650</p>
              <p>✅ Reduction in Missed Messages: 100%</p>
            </div>
          </div>

        </div>
      </div>
    </section>
  );
}
