import { 
  ChatBubbleLeftRightIcon, 
  CpuChipIcon, 
  ClockIcon, 
  CurrencyEuroIcon, 
  CheckCircleIcon 
} from '@heroicons/react/24/outline';

const IMPACT_METRICS = [
  {
    icon: ChatBubbleLeftRightIcon,
    value: "11,733",
    label: "Total Messages Handled",
    color: "from-[#2B00FF]/20 to-[#2B00FF]/5"
  },
  {
    icon: CpuChipIcon,
    value: "81.3%",
    label: "Messages Replied by Chatbot",
    color: "from-[#00D4FF]/20 to-[#00D4FF]/5"
  },
  {
    icon: ClockIcon,
    value: "5.79s",
    label: "Average Response Time",
    color: "from-[#f6db4b]/20 to-[#f6db4b]/5"
  },
  {
    icon: CurrencyEuroIcon,
    value: "€1,650",
    label: "Sales Generated by Chatbot",
    color: "from-[#2B00FF]/20 to-[#00D4FF]/20"
  },
  {
    icon: CheckCircleIcon,
    value: "100%",
    label: "Reduction in Missed Messages",
    color: "from-[#00D4FF]/20 to-[#f6db4b]/20"
  }
];

export default function Milestones() {
  return (
    <section className="w-full py-20 bg-black">
      <div className="w-[80%] mx-auto px-6 md:px-12">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl sm:text-5xl font-bold text-white mb-6">Our Impact in Numbers</h2>
            <p className="text-xl text-gray-400 max-w-3xl mx-auto mb-12">
              Here's how SparkAI is transforming communication for businesses:
            </p>
          </div>

          {/* Statistics Cards */}
          <div className="bg-gradient-to-br from-gray-800/50 to-gray-900/50 rounded-3xl p-8 border border-white/10">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-6">
              {IMPACT_METRICS.map((metric, index) => {
                const IconComponent = metric.icon;
                return (
                  <div key={index} className="text-center">
                    <div className="flex justify-center mb-4">
                      <div className="w-12 h-12 bg-gradient-to-br from-[#D4FF00] to-[#213efa] rounded-xl flex items-center justify-center">
                        <IconComponent className="w-6 h-6 text-black" />
                      </div>
                    </div>
                    <div className="text-2xl sm:text-3xl font-bold text-white mb-2">{metric.value}</div>
                    <div className="text-sm text-gray-300 leading-tight">{metric.label}</div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
